baseURL = "https://www.davidayala.eu"
languageCode = "en-GB"
title = "David Ayala Homepage"
enableRobotsTXT = false

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

assetDir = "static/assets"

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  timeDiff = 7200
  tweetsAPI = "https://spreadsheets.google.com/feeds/cells/1xRcpFi4tL-mKvM4pJUbnQAQ0z3z4AED9lBVqMZKHeZ0/default/public/basic?alt=json"
  testProd = false
