baseURL = "https://www.davidayala.eu"
languageCode = "en-GB"
title = "David Ayala Homepage"
enableRobotsTXT = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  tweetsAPI = "https://spreadsheets.google.com/feeds/cells/1xRcpFi4tL-mKvM4pJUbnQAQ0z3z4AED9lBVqMZKHeZ0/default/public/basic?alt=json"
  uncss = true
