baseURL = "https://www.davidayala.eu"
languageCode = "en-GB"
title = "David Ayala Homepage"
enableRobotsTXT = false

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  testProd = false