baseURL = "https://www.davidayala.eu"
languageCode = "en-GB"
title = "David Ayala Homepage"
enableRobotsTXT = false

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

assetDir = "static/assets"

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  timeDiff = 7200
  testProd = false
