[build]
  functions = "./functions-build"

[build.environment]
  HUGO_VERSION = "0.148.2"

[[headers]]
  for = "*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

[functions."twitter-cron"]
  schedule = "@daily"