backend:
  name: github
  repo: davidayalas/ssg-huguoc 
  branch: master
  base_url: http://netlify-oauth.azurewebsites.net # Path to ext auth provider


media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "home"
    label: "Home"
    folder: "content/"
    create: true
    slug: "home.md"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Keywords", name: "keyworkds", widget: "text", required: true}
      - name: social
        label: Contact
        widget: list
        fields:
          - {label: "Títol", name: "title", widget: string}
          - {label: "Enllaç", name: "link", widget: string}
          - {label: "CSS Class", name: "class", widget: string}
      - name: doingnow
        label: Doing now
        widget: list
        fields:
          - {label: "Ítem", name: "item", widget: markdown}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
