backend:
  name: github
  repo: davidayalas/personal_site 
  #branch: master
  #name: git-gateway

display_url: https://davidayala.eu

media_folder: "/content/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    editor: 
      preview: false     
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: string}
      - {label: "Date", name: "date", widget: date}
      - {label: "Image", name: "image", widget: image}

  - name: "home"
    label: "Home"
    folder: "content"
    create: false
    delete: false
    editor: 
      preview: false 
    slug: "home.md"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "HTML Title", name: "html_title", widget: "string", tagname: "h1"}
      - {label: "Header image", name: "header", widget: "image", required: true}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Message", name: "message", widget: "text", required: true}
      - {label: "Keywords", name: "meta_keywords", widget: "text", required: true}
      - {label: "Doing now", name: "doingnow_title", widget: "string"}
      - {label: "Doing now list", name: "doingnow", widget: "markdown"}
      - {label: "Media title", name: "media", widget: "string"}
      - {label: "Social title", name: "social_title", widget: "string"}
      - name: social
        label: Contact
        widget: list
        fields:
          - {label: "Títol", name: "title", widget: string}
          - {label: "Enllaç", name: "link", widget: string}
          - {label: "CSS Class", name: "class", widget: string}
      - name: miniprojects
        label: Miniprojects
        widget: list
        fields:
          - {label: "Títol", name: "title", widget: string}
          - {label: "Enllaç", name: "link", widget: string}
          - {label: "Descripció", name: "description", widget: string}
      - {label: "Arquitectura", name: "architecture_title", widget: "string", required: false}
      - {label: "Diagrama", name: "architecture_diagram", widget: "image"}
      - {label: "Títol form contacte", name: "contact_title", widget: "string", required: false}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
